import path from "node:path";

import { defineProject } from "vitest/config";

const defaultExclude = ["**/node_modules/**", "**/dist/**"];
const lfccBridgeAlias = path.resolve(__dirname, "packages/lfcc-bridge/src/index.ts");

export default [
  defineProject({
    resolve: {
      alias: {
        "@keepup/agent-runtime": path.resolve(__dirname, "packages/agent-runtime/src/index.ts"),
        "@keepup/ai-core": path.resolve(__dirname, "packages/ai-core/src/index.ts"),
        "@keepup/app": path.resolve(__dirname, "packages/app/src/index.ts"),
        "@keepup/bench": path.resolve(__dirname, "packages/bench/src/index.ts"),
        "@keepup/collab-server-lib": path.resolve(__dirname, "packages/collab-server/src/index.ts"),
        "@keepup/compat": path.resolve(__dirname, "packages/compat/src/index.ts"),
        "@keepup/conformance-kit": path.resolve(__dirname, "packages/conformance-kit/src/index.ts"),
        "@keepup/core": path.resolve(__dirname, "packages/core/src/index.ts"),
        "@keepup/core/sync": path.resolve(__dirname, "packages/core/src/sync/index.ts"),
        "@keepup/core/sync/server": path.resolve(__dirname, "packages/core/src/sync/server.ts"),
        "@keepup/core/security": path.resolve(__dirname, "packages/core/src/security/index.ts"),
        "@keepup/crypto": path.resolve(__dirname, "packages/crypto/src/index.ts"),
        "@keepup/db": path.resolve(__dirname, "packages/db/src/index.ts"),
        "@keepup/db/types": path.resolve(__dirname, "packages/db/src/driver/types.ts"),
        "@keepup/db/web": path.resolve(__dirname, "packages/db/src/web/index.ts"),
        "@keepup/db/worker": path.resolve(__dirname, "packages/db/src/worker/index.ts"),
        "@packages/ingest-file": path.resolve(__dirname, "packages/ingest/file/src/index.ts"),
        "@packages/ingest-rss": path.resolve(__dirname, "packages/ingest/rss/src/index.ts"),
        "@packages/ingest-youtube": path.resolve(__dirname, "packages/ingest-youtube/src/index.ts"),
        "@keepup/lfcc-bridge": lfccBridgeAlias,
        "@keepup/overlay": path.resolve(__dirname, "packages/overlay/src/index.ts"),
        "@keepup/shared": path.resolve(__dirname, "packages/shared/src/index.ts"),
        "@keepup/shared/utils": path.resolve(__dirname, "packages/shared/src/utils/index.ts"),
        "@keepup/shared/ui/motion": path.resolve(__dirname, "packages/shared/src/ui/motion.ts"),
        "@keepup/token": path.resolve(__dirname, "packages/token/src/index.ts"),
        "@keepup/translator": path.resolve(__dirname, "packages/translator/src/index.ts"),
        "@keepup/tts": path.resolve(__dirname, "packages/tts/src/index.ts"),
      },
    },
    test: {
      name: "core-conformance",
      include: [
        "packages/core/src/**/__tests__/**/*.test.ts",
        "packages/conformance-kit/src/**/__tests__/**/*.test.ts",
      ],
      exclude: defaultExclude,
      environment: "node",
    },
  }),
  defineProject({
    resolve: {
      alias: {
        "@keepup/agent-runtime": path.resolve(__dirname, "packages/agent-runtime/src/index.ts"),
        "@keepup/ai-core": path.resolve(__dirname, "packages/ai-core/src/index.ts"),
        "@keepup/app": path.resolve(__dirname, "packages/app/src/index.ts"),
        "@keepup/bench": path.resolve(__dirname, "packages/bench/src/index.ts"),
        "@keepup/collab-server-lib": path.resolve(__dirname, "packages/collab-server/src/index.ts"),
        "@keepup/compat": path.resolve(__dirname, "packages/compat/src/index.ts"),
        "@keepup/conformance-kit": path.resolve(__dirname, "packages/conformance-kit/src/index.ts"),
        "@keepup/core": path.resolve(__dirname, "packages/core/src/index.ts"),
        "@keepup/core/sync": path.resolve(__dirname, "packages/core/src/sync/index.ts"),
        "@keepup/core/sync/server": path.resolve(__dirname, "packages/core/src/sync/server.ts"),
        "@keepup/core/security": path.resolve(__dirname, "packages/core/src/security/index.ts"),
        "@keepup/crypto": path.resolve(__dirname, "packages/crypto/src/index.ts"),
        "@keepup/db": path.resolve(__dirname, "packages/db/src/index.ts"),
        "@keepup/db/types": path.resolve(__dirname, "packages/db/src/driver/types.ts"),
        "@keepup/db/web": path.resolve(__dirname, "packages/db/src/web/index.ts"),
        "@keepup/db/worker": path.resolve(__dirname, "packages/db/src/worker/index.ts"),
        "@packages/ingest-file": path.resolve(__dirname, "packages/ingest/file/src/index.ts"),
        "@packages/ingest-rss": path.resolve(__dirname, "packages/ingest/rss/src/index.ts"),
        "@packages/ingest-youtube": path.resolve(__dirname, "packages/ingest-youtube/src/index.ts"),
        "@keepup/lfcc-bridge": lfccBridgeAlias,
        "@keepup/overlay": path.resolve(__dirname, "packages/overlay/src/index.ts"),
        "@keepup/shared": path.resolve(__dirname, "packages/shared/src/index.ts"),
        "@keepup/shared/utils": path.resolve(__dirname, "packages/shared/src/utils/index.ts"),
        "@keepup/shared/ui/motion": path.resolve(__dirname, "packages/shared/src/ui/motion.ts"),
        "@keepup/token": path.resolve(__dirname, "packages/token/src/index.ts"),
        "@keepup/translator": path.resolve(__dirname, "packages/translator/src/index.ts"),
        "@keepup/tts": path.resolve(__dirname, "packages/tts/src/index.ts"),
      },
    },
    test: {
      name: "collab-server",
      include: ["packages/collab-server/src/**/*.test.ts"],
      exclude: defaultExclude,
      globals: true,
      coverage: {
        reporter: ["text", "json", "html"],
      },
    },
  }),
  defineProject({
    resolve: {
      alias: {
        "@keepup/agent-runtime": path.resolve(__dirname, "packages/agent-runtime/src/index.ts"),
        "@keepup/ai-core": path.resolve(__dirname, "packages/ai-core/src/index.ts"),
        "@keepup/app": path.resolve(__dirname, "packages/app/src/index.ts"),
        "@keepup/bench": path.resolve(__dirname, "packages/bench/src/index.ts"),
        "@keepup/collab-server-lib": path.resolve(__dirname, "packages/collab-server/src/index.ts"),
        "@keepup/compat": path.resolve(__dirname, "packages/compat/src/index.ts"),
        "@keepup/conformance-kit": path.resolve(__dirname, "packages/conformance-kit/src/index.ts"),
        "@keepup/core": path.resolve(__dirname, "packages/core/src/index.ts"),
        "@keepup/core/sync": path.resolve(__dirname, "packages/core/src/sync/index.ts"),
        "@keepup/core/sync/server": path.resolve(__dirname, "packages/core/src/sync/server.ts"),
        "@keepup/core/security": path.resolve(__dirname, "packages/core/src/security/index.ts"),
        "@keepup/crypto": path.resolve(__dirname, "packages/crypto/src/index.ts"),
        "@keepup/db": path.resolve(__dirname, "packages/db/src/index.ts"),
        "@keepup/db/types": path.resolve(__dirname, "packages/db/src/driver/types.ts"),
        "@keepup/db/web": path.resolve(__dirname, "packages/db/src/web/index.ts"),
        "@keepup/db/worker": path.resolve(__dirname, "packages/db/src/worker/index.ts"),
        "@packages/ingest-file": path.resolve(__dirname, "packages/ingest/file/src/index.ts"),
        "@packages/ingest-rss": path.resolve(__dirname, "packages/ingest/rss/src/index.ts"),
        "@packages/ingest-youtube": path.resolve(__dirname, "packages/ingest-youtube/src/index.ts"),
        "@keepup/lfcc-bridge": lfccBridgeAlias,
        "@keepup/overlay": path.resolve(__dirname, "packages/overlay/src/index.ts"),
        "@keepup/shared": path.resolve(__dirname, "packages/shared/src/index.ts"),
        "@keepup/shared/utils": path.resolve(__dirname, "packages/shared/src/utils/index.ts"),
        "@keepup/shared/ui/motion": path.resolve(__dirname, "packages/shared/src/ui/motion.ts"),
        "@keepup/token": path.resolve(__dirname, "packages/token/src/index.ts"),
        "@keepup/translator": path.resolve(__dirname, "packages/translator/src/index.ts"),
        "@keepup/tts": path.resolve(__dirname, "packages/tts/src/index.ts"),
      },
    },
    test: {
      name: "app-jsdom",
      include: ["packages/app/src/**/*.test.ts"],
      exclude: defaultExclude,
      environment: "jsdom",
    },
  }),
  defineProject({
    resolve: {
      alias: {
        "@keepup/agent-runtime": path.resolve(__dirname, "packages/agent-runtime/src/index.ts"),
        "@keepup/ai-core": path.resolve(__dirname, "packages/ai-core/src/index.ts"),
        "@keepup/app": path.resolve(__dirname, "packages/app/src/index.ts"),
        "@keepup/bench": path.resolve(__dirname, "packages/bench/src/index.ts"),
        "@keepup/collab-server-lib": path.resolve(__dirname, "packages/collab-server/src/index.ts"),
        "@keepup/compat": path.resolve(__dirname, "packages/compat/src/index.ts"),
        "@keepup/conformance-kit": path.resolve(__dirname, "packages/conformance-kit/src/index.ts"),
        "@keepup/core": path.resolve(__dirname, "packages/core/src/index.ts"),
        "@keepup/core/sync": path.resolve(__dirname, "packages/core/src/sync/index.ts"),
        "@keepup/core/sync/server": path.resolve(__dirname, "packages/core/src/sync/server.ts"),
        "@keepup/core/security": path.resolve(__dirname, "packages/core/src/security/index.ts"),
        "@keepup/crypto": path.resolve(__dirname, "packages/crypto/src/index.ts"),
        "@keepup/db": path.resolve(__dirname, "packages/db/src/index.ts"),
        "@keepup/db/types": path.resolve(__dirname, "packages/db/src/driver/types.ts"),
        "@keepup/db/web": path.resolve(__dirname, "packages/db/src/web/index.ts"),
        "@keepup/db/worker": path.resolve(__dirname, "packages/db/src/worker/index.ts"),
        "@packages/ingest-file": path.resolve(__dirname, "packages/ingest/file/src/index.ts"),
        "@packages/ingest-rss": path.resolve(__dirname, "packages/ingest/rss/src/index.ts"),
        "@packages/ingest-youtube": path.resolve(__dirname, "packages/ingest-youtube/src/index.ts"),
        "@keepup/lfcc-bridge": lfccBridgeAlias,
        "@keepup/overlay": path.resolve(__dirname, "packages/overlay/src/index.ts"),
        "@keepup/shared": path.resolve(__dirname, "packages/shared/src/index.ts"),
        "@keepup/shared/utils": path.resolve(__dirname, "packages/shared/src/utils/index.ts"),
        "@keepup/shared/ui/motion": path.resolve(__dirname, "packages/shared/src/ui/motion.ts"),
        "@keepup/token": path.resolve(__dirname, "packages/token/src/index.ts"),
        "@keepup/translator": path.resolve(__dirname, "packages/translator/src/index.ts"),
        "@keepup/tts": path.resolve(__dirname, "packages/tts/src/index.ts"),
      },
    },
    test: {
      name: "packages-default",
      include: [
        "packages/lfcc-bridge/src/**/*.test.ts",
        "packages/overlay/src/**/*.test.ts",
        "packages/compat/src/**/*.test.ts",
        "packages/ingest-youtube/src/**/*.test.ts",
        "packages/agent-runtime/src/**/*.test.ts",
      ],
      exclude: defaultExclude,
    },
  }),
];
