/**
 * Plugins Module (Facade)
 *
 * Re-export plugin APIs while avoiding name collisions with core Tool types.
 */

export type {
  ActivationEvent,
  AfterAgentRunHookData,
  AfterLLMCallHookData,
  AfterToolCallHookData,
  AgentContribution,
  AgentFactoryConfig,
  BeforeAgentRunHookData,
  BeforeLLMCallHookData,
  BeforeToolCallHookData,
  CommandContribution,
  CommandHandler,
  ConfigurationContribution,
  DependencyGraph,
  Disposable,
  HookHandler,
  HookType,
  IPlugin,
  IPluginAgent,
  IPluginRegistry,
  IPluginResolver,
  MissingDependency,
  PluginAgentFactory,
  PluginAgentRunResult,
  PluginCapability,
  PluginContext,
  PluginContributes,
  PluginDependency,
  PluginInfo,
  PluginLoaderConfig,
  PluginLogger,
  PluginManifest,
  PluginRegistryEntry,
  PluginSearchQuery,
  PluginSearchResult,
  PluginState,
  PluginToolExecutionContext,
  PluginToolHandler,
  PluginToolResult,
  PluginType,
  Progress,
  ResolutionResult,
  ToolContribution,
  VersionConflict,
} from "@ku0/agent-runtime-tools/plugins";
export {
  BasePlugin,
  Command,
  createDependencyResolver,
  createPluginLoader,
  createPluginRegistry,
  FileSystemPluginResolver,
  Hook,
  InMemoryPluginRegistry,
  NPMPluginResolver,
  PluginDependencyResolver,
  PluginLoader,
  satisfiesVersion,
  Tool as PluginTool,
} from "@ku0/agent-runtime-tools/plugins";
