/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function stringify(value: any): NapiResult
export declare function parse(text: string): NapiResult
export declare function stableStringify(value: any): NapiResult
